name = "简单flag扫描"
# The name of this task
author = "AutoVol3"
# Author name
arch = "windows"
# The arch of target, e.g. windows | mac | linux
[settings]
# Main Settings
parent = ["parent-task1", "parent-task2"]
# The parent task, your task will execute these parent tasks before this task
tasks = ["windows.info"]
# Volatility3 commands
findstr = ["123456", "abcdef", "ABCDEF"]
# Find target strings in output and parent tasks' output, AutoVol3 will try to find these strings and save them in the end of output file
regex = [
    "^\\w+([-+.\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*$"
]
# Find target strings in output and parent tasks' output, same as above, but use regex
dumpfiles = false
# If you set "true", AutoVol3 will try to dump matched files after this task
[output]
console = false
# Output full content to the console
